imagePullSecret: regcred-vpc
container:
  env:
    - name: GIN_MODE
      value: release
  port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  livenessProbe: 
    enabled: false
  readinessProbe:
    enabled: false
  volumeMounts:
    - mountPath: /app/config.yaml
      subPath: config.yaml
      name: devops-links-config
      readOnly: false
    - mountPath: /app/data/uploads/icons
      name: devops-links-uploads
volumes:
  - name: devops-links-config
    configMap:
      name: devops-links-config
  - name: devops-links-uploads
    persistentVolumeClaim:
      claimName: devops-links-uploads
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http